### ISSUE TITLE
Errors running OPRDatacard, no output

### ISSUE THREAD

**Issue by Mirakna** [JackGruber/GDFDataCards#4]
When trying to run the script, I got these errors. Seems like OPR have updated some definitions and the script doesn't know them yet?
[Error 1.txt](https://github.com/JackGruber/OPRDataCards/files/14824706/Error.1.txt)
[Error 2.txt](https://github.com/JackGruber/OPRDataCards/files/14824707/Error.2.txt)

**Comment by JackGruber** [comment]
Could you please post your army json file.

**Comment by Mirakna** [comment]
Sure! 
[Necrons Combat Patrol 1.2kocjUa4aH72ba.json](https://github.com/JackGruber/OPRDataCards/files/14827586/Necrons.Combat.Patrol.1.2kocjUa4aH72ba.json)

And here the link to the Army Forge
https://army-forge.onepagerules.com/share?id=ocjUa4aH72ba&name=Necrons_Combat%20Patrol%201.2k

**Comment by JackGruber** [comment]
Fixed in v1.1.2 82276a8
